# -*- coding: utf-8 -*-
#
# High Level Systems Administration documentation build configuration file, created by
# sphinx-quickstart on Thu Oct 20 09:29:36 2011.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

needs_sphinx = '1.0'
extensions = ["sphinx.ext.intersphinx", "sphinx.ext.extlinks"]
templates_path = ['.templates']
source_suffix = '.txt'
master_doc = 'index'

project = u'tychoish'
copyright = u'2012, Sam Kleinman (tychoish/tycho garen)'

version = '1.0'
release = version

exclude_patterns = []

pygments_style = 'sphinx'

extlinks = {
    'project': ('/projects/%s', ''),
    'institute': ('http://cyborginstitute.com/%s', ''),
    'issues': ('http://issues.cyborginstitute.com/%s', ''),
    'list': ('http://lists.cyborginstitute.com/listinfo/%s', ''),
    'git': ('http://git.cyborginstitute.com/%s', ''),
    'github': ('http://github.com/cyborginstitute/%s', '')
    }


# -- Options for HTML output ---------------------------------------------------

git_name = 'tychoweb'
html_theme_options = { 'project': git_name }
html_theme = 'tychoish'

html_theme_path = ['themes']
